### ISSUE TITLE
Extremely large tile/flat cube used as background behaves incorrectly

### ISSUE THREAD

**Issue by jakusb** [MasahideMori1111/simple_3d#5]
I am drawing a 3d world on a flat surface to represent a factory floor.
As all drawings hover in thin air, I decided to draw a tile where the ground should be.
However such a big tile is drawn incorrectly. Eventhough it is bigger then everything else and is on z=-5 elevation, it covers the outer boxes that are on a z>0.

First screenshot at z=-15, second at z=-500
![image](https://github.com/MasahideMori-SimpleAppli/simple_3d/assets/9477833/7185bf47-79b3-47d8-9ea7-fc19924af3a2)
![image](https://github.com/MasahideMori-SimpleAppli/simple_3d/assets/9477833/7f450c32-691e-42b8-a07f-b1ecfe5d1333)

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @jakusb !
Thank you for opening this issue.

Perhaps this is due to the default camera.
The default camera uses a very simple algorithm to calculate the position information for each surface.
Therefore, in a scenario where one huge surface is placed behind the main object, the drawing context may be broken depending on the angle and distance.

There are several ways to work around this issue.
The following is probably the most efficient workaround.

1. Set the layerNum variable of the back object (Sp3dObj) to a smaller value than the front object, such as -3.
2. Set the useLayer flag of Sp3dWorld to true and initialize it as in the example below.
```
       _world = Sp3dWorld(_objs, useLayer: true).initLayer();
       _world!.initImages().then((List<Sp3dObj> errorObjs) {
         // Your screen update code. e.g. setState.
       });
```
